//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Navigation_Drawer_App.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Output
    {
        public int Id { get; set; }
        public int idObject { get; set; }
        public int Price { get; set; }
        public int Count { get; set; }
        public int IdCustomer { get; set; }
        public Nullable<System.DateTime> DateOutput { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Object Object { get; set; }
    }
}
